# Generated by Django 2.0.6 on 2018-06-10 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='authorInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_bio', models.CharField(max_length=1000)),
                ('author_linkedIn', models.CharField(max_length=1000)),
                ('author_facebook', models.CharField(max_length=1000)),
                ('author_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.author')),
            ],
        ),
        migrations.DeleteModel(
            name='mainInfo',
        ),
    ]
