# Generated by Django 2.0.6 on 2018-06-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180610_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorinfo',
            name='author_photo',
            field=models.CharField(default='profile.jpg', max_length=1000),
            preserve_default=False,
        ),
    ]
